"""empty message

Revision ID: 377342da1151
Revises: 01bb93a6f3ae
Create Date: 2020-12-23 08:56:51.436544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377342da1151'
down_revision = '01bb93a6f3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
